import { Inter, Noto_Sans_JP } from "next/font/google";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  variable: "--font-noto-sans-jp",
});

export const metadata = {
  title: "Create medical app",
  description: "Generated by create medical app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${notoSansJP.variable} ${inter.variable}`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
