import { Inter, Noto_Sans_JP } from "next/font/google";
import "./globals.scss";
import Header from "@/components/Layout/Header/Header";
import Footer from "@/components/Layout/Footer/Footer";
import dynamic from "next/dynamic";

const ScrollButton = dynamic(() => import("@/components/ScrollButton/ScrollButton"), { ssr: false });

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  variable: "--font-noto-sans-jp",
});

export const metadata = {
  title: "Medical app",
  description: "Generated by create medical app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${notoSansJP.variable} ${inter.variable}`}>
        <main className={"text-ds-dark-500"}>
          <Header />
          {children}
          <Footer />
          <ScrollButton/>
        </main>
      </body>
    </html>
  );
}
